/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join */
        post: operations["join_agents__agent_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workstreams/{ws_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim */
        post: operations["claim_workstreams__ws_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workstreams/{ws_id}/declare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Declare */
        post: operations["declare_workstreams__ws_id__declare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workstreams/{ws_id}/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reassign Scope */
        post: operations["reassign_scope_workstreams__ws_id__scope_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workstreams/{ws_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_workstreams__ws_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Local demo only. Restores the seeded fixture.
         */
        post: operations["reset_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentPrincipal */
        AgentPrincipal: {
            /** Id */
            id: string;
            /** Ans Name */
            ans_name: string;
            /** Role */
            role: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /** ApiContract */
        ApiContract: {
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
            /** Path */
            path: string;
            /**
             * Role
             * @enum {string}
             */
            role: "provides" | "consumes";
            /** Request Fields */
            request_fields?: {
                [key: string]: string;
            };
            /** Response Fields */
            response_fields?: {
                [key: string]: string;
            };
        };
        /** ChangeSet */
        ChangeSet: {
            /** Id */
            id: string;
            /** Workstream Id */
            workstream_id: string;
            /** Agent Id */
            agent_id: string;
            /** Commit Sha */
            commit_sha?: string | null;
            /** Files */
            files: string[];
            contract: components["schemas"]["ApiContract"];
            /** Tests */
            tests?: components["schemas"]["TestResult"][];
        };
        /** ClaimRequest */
        ClaimRequest: {
            /** Agent Id */
            agent_id: string;
        };
        /** Conflict */
        Conflict: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "file" | "contract";
            /** Workstream Ids */
            workstream_ids: string[];
            /** Explanation */
            explanation: string;
            /** Conflicting Field */
            conflicting_field: string;
            /** Decision Id */
            decision_id?: string | null;
            /** Recommendation */
            recommendation: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "resolved";
        };
        /** Decision */
        Decision: {
            /** Decision Id */
            decision_id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Affected Component */
            affected_component: string;
            /** Created At */
            created_at: string;
        };
        /** DeclareRequest */
        DeclareRequest: {
            /** Agent Id */
            agent_id: string;
            contract: components["schemas"]["ApiContract"];
        };
        /** Event */
        Event: {
            /** Event Id */
            event_id: string;
            /** Objective Id */
            objective_id: string;
            /** Workstream Id */
            workstream_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Identity Mode */
            identity_mode: string;
            /** Memory Mode */
            memory_mode: string;
            /**
             * Live Integrations
             * @default false
             */
            live_integrations: boolean;
        };
        /** Objective */
        Objective: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Acceptance Criteria */
            acceptance_criteria: string[];
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "complete";
        };
        /** ScopeRequest */
        ScopeRequest: {
            /** Agent Id */
            agent_id: string;
            /** Owned Paths */
            owned_paths: string[];
        };
        /** TestResult */
        TestResult: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "not_run";
            /**
             * Source
             * @default agent_reported
             * @enum {string}
             */
            source: "agent_reported" | "synapse_executed";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceState */
        WorkspaceState: {
            /**
             * Phase
             * @default foundation
             * @constant
             */
            phase: "foundation";
            objective?: components["schemas"]["Objective"] | null;
            /** Workstreams */
            workstreams?: components["schemas"]["Workstream"][];
            /** Agents */
            agents?: components["schemas"]["AgentPrincipal"][];
            /** Conflicts */
            conflicts?: components["schemas"]["Conflict"][];
            /** Decisions */
            decisions?: components["schemas"]["Decision"][];
            /** Events */
            events?: components["schemas"]["Event"][];
        };
        /** Workstream */
        Workstream: {
            /** Id */
            id: string;
            /** Objective Id */
            objective_id: string;
            /** Title */
            title: string;
            /** Agent Id */
            agent_id: string;
            /** Owned Paths */
            owned_paths: string[];
            /** Depends On */
            depends_on?: string[];
            contract: components["schemas"]["ApiContract"];
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "active" | "blocked" | "complete";
            latest_changeset?: components["schemas"]["ChangeSet"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    state_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
        };
    };
    join_agents__agent_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_workstreams__ws_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    declare_workstreams__ws_id__declare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_scope_workstreams__ws_id__scope_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_workstreams__ws_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
        };
    };
}
