import { useEffect, useReducer, useState, type KeyboardEvent } from 'react';
import { Activity, ArrowRight, ArrowUpRight, BookOpen, Box, Check, CheckCheck, Circle, CircleHelp, CirclePlay, Code2, Database, Download, FileCode2, FolderGit2, GitBranch, GitCompareArrows, GitMerge, Layers3, LockKeyhole, Menu, Network, Plug, RotateCcw, ShieldCheck, Terminal, TriangleAlert, X } from 'lucide-react';
import { AgentCard, Badge, Busy, Button, Diff, FileList, InspectorDrawer, Logo, TestRows, type Inspector } from './components';
import { decisions, demoFiles, demoReducer, demoTests, hasIdentity, initialDemo, isAligned, type DemoState, type Phase } from './demo';
import { useBackend } from './useBackend';

type Page = 'workspace' | 'repository' | 'memory' | 'integrations';
type Tab = 'workstreams' | 'changes' | 'review';
const pages: { id: Page; label: string; icon: typeof Layers3 }[] = [
  { id: 'workspace', label: 'Workspace', icon: Layers3 },
  { id: 'repository', label: 'Repository', icon: FolderGit2 },
  { id: 'memory', label: 'Project memory', icon: BookOpen },
  { id: 'integrations', label: 'Integrations', icon: Plug },
];

export function App() {
  const [demo, dispatch] = useReducer(demoReducer, initialDemo);
  const [page, setPage] = useState<Page>('workspace');
  const [tab, setTab] = useState<Tab>('workstreams');
  const [mode, setMode] = useState<'demo' | 'backend'>('demo');
  const [inspector, setInspector] = useState<Inspector>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [resetConfirm, setResetConfirm] = useState(false);
  const [selectedFile, setSelectedFile] = useState(0);
  const [toast, setToast] = useState('');
  const backend = useBackend();

  useEffect(() => {
    if (mode !== 'demo') return;
    const steps = { verifying: ['verified', 1400], context: ['declared', 1800], correcting: ['redeclared', 1700], submitting: ['completed', 1600] } as const;
    if (!(demo.phase in steps)) return;
    const [type, delay] = steps[demo.phase as keyof typeof steps];
    const timer = setTimeout(() => dispatch({ type }), delay);
    return () => clearTimeout(timer);
  }, [demo.phase, mode]);

  useEffect(() => {
    if (demo.phase === 'complete') setTab('review');
  }, [demo.phase]);

  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(''), 4500);
    return () => clearTimeout(timer);
  }, [toast]);

  const navigate = (next: Page) => { setPage(next); setMobileNav(false); };
  const start = () => { setPage('workspace'); setTab('workstreams'); dispatch({ type: 'start' }); };
  const reset = () => { dispatch({ type: 'reset' }); setResetConfirm(false); setTab('workstreams'); setPage('workspace'); setToast('Demo reset. Backend data was not changed.'); };
  const selectFile = (index: number) => { setSelectedFile(index); setPage('repository'); };
  const exportReview = () => {
    if (demo.phase !== 'complete') return;
    const report = { title: 'Synapse · OAuth Convergence review', source: 'FRONTEND SIMULATION — not live sponsor evidence', outcome: 'Ready for review; no merge performed', files: demoFiles.map(file => file.path), identity: 'Mock fixtures; no ANS verification', memory: 'Local decision fixtures; no Databricks write', tests: demoTests.map(test => ({ ...test, status: 'passed', source: 'simulated_agent_report' })), contract: { token: 'string', user: 'object' }, events: demo.events };
    const url = URL.createObjectURL(new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' }));
    const link = document.createElement('a'); link.href = url; link.download = 'synapse-demo-review.json'; link.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000); setToast('Demo review exported with evidence labels.');
  };

  return <div className="app-shell">
    <a className="skip-link" href="#main-content">Skip to workspace</a>
    <aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`} aria-label="Workspace navigation">
      <div className="sidebar-brand"><Logo /><button className="icon-button mobile-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X size={19} /></button></div>
      <div className="team-switch"><div className="team-avatar">S</div><div><strong>Synapse team</strong><span>Hackathon workspace</span></div><Badge>Demo</Badge></div>
      <nav className="primary-nav" aria-label="Main navigation">{pages.map(item => <button key={item.id} className={`nav-item ${page === item.id ? 'current' : ''}`} aria-current={page === item.id ? 'page' : undefined} onClick={() => navigate(item.id)}><item.icon size={18} /><span>{item.label}</span>{item.id === 'workspace' && <span className="nav-count">1</span>}</button>)}</nav>
      <div className="sidebar-objectives"><span className="sidebar-label">Active objective</span><button className="objective-nav" onClick={() => { navigate('workspace'); setTab('workstreams'); }}><span className={`status-dot ${demo.phase === 'complete' ? 'complete' : 'active'}`} /><span>Organization OAuth</span></button><div className="objective-branch"><GitBranch size={13} /><span>2 workstreams</span></div></div>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => setInspector({ kind: 'guide' })}><CircleHelp size={18} />Demo walkthrough<ArrowUpRight size={14} /></button><div className="sidebar-divider" /><div className="user-row"><span className="user-avatar">SY</span><div><strong>Local workspace</strong><span>No account required</span></div><span className="status-dot active" /></div></div>
    </aside>
    {mobileNav && <button className="nav-scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}

    <div className="app-main"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={20} /></button><FolderGit2 size={17} /><span className="repo-owner">synapse</span><span className="slash">/</span><strong>oauth-demo</strong><Badge><GitBranch size={12} />main</Badge></div><div className="topbar-right"><button className="connection-link" onClick={() => { setPage('integrations'); }}><span className={`status-dot ${backend.error ? 'offline' : backend.data ? 'active' : 'waiting'}`} />{backend.error ? 'Backend offline' : backend.data ? 'Backend connected' : 'Connecting'}</button><a className="icon-button" href="https://github.com/Jeewant05/VT-Hacks-14-Project" target="_blank" rel="noreferrer" aria-label="Open source repository on GitHub"><ArrowUpRight size={18} /></a></div></header>

      <div className="environment-bar"><div><Box size={15} /><strong>{mode === 'demo' ? 'Interactive demo' : 'Backend workspace'}</strong><span>{mode === 'demo' ? 'Simulated agents & evidence. No repository changes.' : 'Read-only API data. Demo state is kept separate.'}</span></div><div className="mode-switch" aria-label="Data source"><button aria-pressed={mode === 'demo'} onClick={() => setMode('demo')}>Demo</button><button aria-pressed={mode === 'backend'} onClick={() => setMode('backend')}>Backend</button></div></div>

      <main id="main-content" tabIndex={-1}>
        {mode === 'backend' ? <BackendView backend={backend} onDemo={() => setMode('demo')} /> : <>
          {page === 'workspace' && <><div className="objective-header"><div className="objective-meta"><span className="objective-id"><Network size={14} />Objective SYN-001</span><Badge tone={demo.phase === 'complete' ? 'green' : demo.phase === 'conflict' || demo.phase === 'correcting' ? 'amber' : 'neutral'}>{demo.phase === 'complete' ? 'Ready for review' : demo.phase === 'conflict' || demo.phase === 'correcting' ? 'Needs attention' : 'In progress'}</Badge></div><div className="objective-title-row"><div><h1>Add organization-level OAuth login</h1><p>Two agents. A shared contract. One coordinated outcome.</p></div><div className="objective-actions">{demo.phase !== 'ready' && <Button variant="quiet" onClick={() => setResetConfirm(true)}><RotateCcw size={14} />Reset demo</Button>}{demo.phase === 'ready' && <Button variant="primary" onClick={start}><CirclePlay size={16} />Start demo</Button>}{demo.phase === 'complete' && <Button onClick={exportReview}><Download size={15} />Export review</Button>}</div></div><div className="acceptance-list"><span><Check size={13} />Explicit work boundaries</span><span>{hasIdentity(demo.phase) ? <Check size={13} /> : <Circle size={11} />}Agent identities</span><span>{isAligned(demo.phase) ? <Check size={13} /> : <Circle size={11} />}Compatible contracts</span><span>{demo.phase === 'complete' ? <Check size={13} /> : <Circle size={11} />}Combined review</span></div></div>
          <Progress phase={demo.phase} />
          <div className="workspace-tabs" role="tablist" aria-label="Objective sections" onKeyDown={(event: KeyboardEvent<HTMLDivElement>) => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const values: Tab[] = ['workstreams', 'changes', 'review']; const index = values.indexOf(tab); const next = event.key === 'Home' ? 0 : event.key === 'End' ? 2 : (index + (event.key === 'ArrowRight' ? 1 : 2)) % 3; setTab(values[next]); event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]')[next].focus(); }}>
            <button role="tab" id="tab-workstreams" aria-controls="objective-panel" aria-selected={tab === 'workstreams'} tabIndex={tab === 'workstreams' ? 0 : -1} onClick={() => setTab('workstreams')}><Network size={16} />Workstreams<span>2</span></button>
            <button role="tab" id="tab-changes" aria-controls="objective-panel" aria-selected={tab === 'changes'} tabIndex={tab === 'changes' ? 0 : -1} onClick={() => setTab('changes')}><GitCompareArrows size={16} />Changes<span>{demo.phase === 'complete' ? '4' : '0'}</span></button>
            <button role="tab" id="tab-review" aria-controls="objective-panel" aria-selected={tab === 'review'} tabIndex={tab === 'review' ? 0 : -1} onClick={() => setTab('review')}><GitMerge size={16} />Convergence{demo.phase !== 'complete' && <LockKeyhole size={12} />}</button>
          </div>
          <div className="workspace-grid"><div className="workspace-content" role="tabpanel" id="objective-panel" aria-labelledby={`tab-${tab}`}>
            {tab === 'workstreams' && <><div className="section-heading"><h2>Workstreams</h2><span className="muted">{demo.phase === 'complete' ? '2 complete' : '1 dependency'}</span></div><div className="agent-pair"><AgentCard role="backend" phase={demo.phase} inspect={setInspector} /><span className={`dependency-line ${isAligned(demo.phase) ? 'dependency-aligned' : ''}`} aria-label="Backend provides the frontend contract"><ArrowRight size={17} /></span><AgentCard role="frontend" phase={demo.phase} inspect={setInspector} /></div><StagePanel demo={demo} start={start} inspect={setInspector} accept={() => dispatch({ type: 'accept' })} submit={() => dispatch({ type: 'submit' })} openReview={() => setTab('review')} />
            <div className="scope-summary"><ShieldCheck size={15} /><span>Scopes are isolated.</span><code>src/api/auth/**</code><span className="scope-separator">and</span><code>src/components/login/**</code><span className="scope-clear">No file overlap</span></div></>}
            {tab === 'changes' && <><div className="section-heading"><h2>ChangeSets</h2><Badge>{demo.phase === 'complete' ? '2 submitted · Demo' : 'Awaiting submissions'}</Badge></div><p className="section-description">{demo.phase === 'complete' ? 'Both workstreams have submitted compatible sample manifests. Select a file to inspect its illustrative changes.' : 'The demo includes four sample files. They become submitted manifests only after the contracts align.'}</p><FileList onSelect={selectFile} submitted={demo.phase === 'complete'} /><div className="inline-note"><FileCode2 size={16} />Sample manifests only. No files in your Git repository are modified.</div></>}
            {tab === 'review' && <Review demo={demo} inspect={setInspector} exportReview={exportReview} onWorkstreams={() => setTab('workstreams')} onFile={selectFile} />}
          </div><ActivityFeed demo={demo} inspect={setInspector} /></div></>}
          {page === 'repository' && <div className="destination-page"><div className="page-heading"><div><h1>Repository</h1><p>Inspect the files behind the two workstreams.</p></div><Badge>Illustrative demo repository</Badge></div><div className="repo-toolbar"><span><GitBranch size={15} />main</span><span>oauth-demo / src</span><span className="muted">4 sample files</span></div><FileList selected={selectedFile} onSelect={setSelectedFile} submitted={demo.phase === 'complete'} /><Diff index={selectedFile} /><div className="inline-note"><CircleHelp size={16} />These excerpts are authored demo material. The actual project lives in VT-Hacks-14-Project.</div></div>}
          {page === 'memory' && <div className="destination-page"><div className="page-heading"><div><h1>Project memory</h1><p>The decisions that keep independent agents working from the same context.</p></div><Badge tone="amber">Local fixtures</Badge></div><div className="memory-intro"><Database size={21} /><div><strong>Governed decisions, at the point of work.</strong><p>The live integration will retrieve these decisions from Databricks. This demo uses three local examples.</p></div></div><div className="decision-list">{decisions.map(decision => <button className="decision-row" key={decision.id} onClick={() => setInspector({ kind: 'decision', id: decision.id })}><BookOpen size={20} /><div><div className="decision-title"><h2>{decision.title}</h2>{decision.relevant && <Badge tone="green">Relevant to objective</Badge>}</div><p>{decision.summary}</p><span>{decision.id} <span className="separator-dot">·</span> {decision.component} <span className="separator-dot">·</span> Local copy</span></div><ArrowUpRight size={17} /></button>)}</div></div>}
          {page === 'integrations' && <Integrations backend={backend} inspect={setInspector} />}
        </>}
      </main>
      <footer className="workspace-footer"><span><span className="status-dot waiting" />{mode === 'demo' ? 'Demo environment' : 'Read-only backend'}</span><span>Built for coordination. Grounded in evidence.</span><span>Synapse / MVP</span></footer>
    </div>
    <InspectorDrawer value={inspector} onClose={() => setInspector(null)} demo={demo} />
    {resetConfirm && <div className="reset-confirm" role="alert"><div><strong>Reset this demo?</strong><span>Clear the local walkthrough and start again. Backend state is unaffected.</span></div><Button onClick={() => setResetConfirm(false)}>Keep progress</Button><Button variant="primary" onClick={reset}>Reset demo</Button></div>}
    <div className={`toast ${toast ? 'toast-visible' : ''}`} role="status">{toast && <><Check size={16} />{toast}</>}</div>
    <div className="sr-only" role="status">{demo.phase === 'conflict' ? 'Contract mismatch detected. Review the recommended correction.' : demo.phase === 'aligned' ? 'Contracts aligned. Submit demo ChangeSets to continue.' : demo.phase === 'complete' ? 'Demo complete. Convergence review is available.' : ''}</div>
  </div>;
}

function Progress({ phase }: { phase: Phase }) {
  const step = phase === 'ready' ? 0 : ['verifying', 'context'].includes(phase) ? 1 : phase === 'complete' ? 3 : 2;
  return <ol className="progress-steps" aria-label="Objective progress">{['Objective created', 'Agents connected', 'Contracts aligned', 'Ready for review'].map((label, index) => <li key={label} className={`${index < step || phase === 'complete' ? 'done' : ''} ${index === step ? 'current' : ''} ${index === 2 && ['conflict', 'correcting'].includes(phase) ? 'attention' : ''}`} aria-current={index === step ? 'step' : undefined}><span>{index < step || phase === 'complete' ? <Check size={13} /> : index === 2 && ['conflict', 'correcting'].includes(phase) ? <TriangleAlert size={12} /> : <span>{index + 1}</span>}</span><span>{index === 2 && ['conflict', 'correcting'].includes(phase) ? 'Contract conflict' : label}</span></li>)}</ol>;
}

function StagePanel({ demo, start, accept, submit, inspect, openReview }: { demo: DemoState; start: () => void; accept: () => void; submit: () => void; inspect: (value: Inspector) => void; openReview: () => void }) {
  const { phase } = demo;
  if (phase === 'ready' || phase === 'verifying' || phase === 'context') return <section className="ready-panel"><div className="ready-diagram" aria-hidden="true"><Code2 size={23} /><span /><Network size={25} /><span /><Code2 size={23} /></div><h2>{phase === 'ready' ? 'Catch the conflict before the code.' : phase === 'verifying' ? 'Checking agent identities…' : 'Agents are declaring their plans…'}</h2><p>{phase === 'ready' ? 'Follow two agents as they declare their intent, reveal a contract mismatch, and find a shared path forward.' : phase === 'verifying' ? 'The walkthrough is using local identity fixtures, not live ANS verification.' : 'Each agent receives its scope, dependency, and the authentication decision.'}</p>{phase === 'ready' ? <Button variant="primary" onClick={start}><CirclePlay size={16} />Start guided demo<ArrowRight size={15} /></Button> : <Busy>{phase === 'verifying' ? 'Checking demo identities' : 'Comparing declared contracts'}</Busy>}<span className="ready-footnote">{phase === 'ready' ? 'About 30 seconds · You control the correction' : 'Simulated step · No external request'}</span></section>;
  return <section className={`coordination-panel ${isAligned(phase) ? 'panel-aligned' : 'panel-conflict'}`} aria-labelledby="coordination-title"><div className="coordination-heading"><div className="coordination-icon">{isAligned(phase) ? <CheckCheck size={21} /> : <GitCompareArrows size={21} />}</div><div><h2 id="coordination-title">{phase === 'complete' ? 'One conflict prevented.' : isAligned(phase) ? 'Both agents now speak the same language.' : 'A contract mismatch. Caught before merge.'}</h2><p>{phase === 'complete' ? 'The two workstreams are ready for a combined review.' : isAligned(phase) ? 'Frontend redeclared the approved response. No open contract conflicts.' : 'The frontend expects field names the backend will not return.'}</p></div><Badge tone={isAligned(phase) ? 'green' : 'amber'}>{isAligned(phase) ? 'Resolved' : 'Blocked'}</Badge></div>
    <div className="comparison"><div className="comparison-label"><span>POST /api/oauth</span><button onClick={() => inspect({ kind: 'contract' })}>Inspect contract<ArrowUpRight size={13} /></button></div><div className="comparison-columns"><div><span className="field-label">Backend provides</span><pre>{'{'}<br /><span className="code-good">  token</span><span className="code-type">: string,</span><br /><span className="code-good">  user</span><span className="code-type">: object</span><br />{'}'}</pre></div><div className="compare-bridge" aria-hidden="true">{isAligned(phase) ? <Check size={18} /> : <GitCompareArrows size={18} />}</div><div><span className="field-label">{isAligned(phase) ? 'Frontend now consumes' : 'Frontend expects'}</span><pre>{'{'}<br /><span className={isAligned(phase) ? 'code-good' : 'code-bad'}>  {isAligned(phase) ? 'token' : 'accessToken'}</span><span className="code-type">: string,</span><br /><span className={isAligned(phase) ? 'code-good' : 'code-bad'}>  {isAligned(phase) ? 'user' : 'profile'}</span><span className="code-type">: object</span><br />{'}'}</pre></div></div></div>
    <button className="decision-evidence" onClick={() => inspect({ kind: 'decision' })}><Database size={19} /><span><strong>Project memory has the answer.</strong><span>ADR-001 requires <code>token</code> and <code>user</code> for authentication responses.</span><small>Databricks decision · Local demo copy</small></span><ArrowUpRight size={17} /></button>
    <div className="resolution-action"><span>{phase === 'conflict' ? 'Update the frontend to the approved contract.' : phase === 'correcting' ? 'Correction accepted. Waiting for redeclaration.' : phase === 'aligned' ? 'Next: collect both manifests and reported tests.' : phase === 'submitting' ? 'Collecting sample manifests and test reports.' : 'No merge performed. The final decision stays yours.'}</span>{phase === 'conflict' ? <Button variant="primary" onClick={accept}>Accept correction<ArrowRight size={15} /></Button> : phase === 'correcting' ? <Button disabled><Busy>Awaiting frontend</Busy></Button> : phase === 'aligned' ? <Button variant="primary" onClick={submit}>Submit demo ChangeSets<ArrowRight size={15} /></Button> : phase === 'submitting' ? <Button disabled><Busy>Checking manifests</Busy></Button> : <Button variant="primary" onClick={openReview}>Open review<ArrowRight size={15} /></Button>}</div>
  </section>;
}

function ActivityFeed({ demo, inspect }: { demo: DemoState; inspect: (value: Inspector) => void }) {
  const [filter, setFilter] = useState<'all' | 'important'>('all');
  const events = demo.events.filter(event => filter === 'all' || event.evidence);
  return <aside className="activity-panel" aria-label="Coordination activity"><div className="activity-heading"><h2><Activity size={17} />Activity</h2><span className="source-tag">Simulated</span></div><div className="activity-filter"><button aria-pressed={filter === 'all'} onClick={() => setFilter('all')}>All events<span>{demo.events.length}</span></button><button aria-pressed={filter === 'important'} onClick={() => setFilter('important')}>Evidence</button></div><ol className="timeline">{events.map(event => <li key={event.id} className={`event-${event.tone}`}><span className="event-marker">{event.tone === 'success' ? <Check size={11} /> : event.tone === 'warning' ? <TriangleAlert size={10} /> : <span />}</span><div className="event-content"><div><strong>{event.title}</strong><time>{event.time}</time></div><p>{event.detail}</p>{event.evidence && <button onClick={() => inspect({ kind: event.evidence! })}>View evidence<ArrowUpRight size={12} /></button>}</div></li>)}</ol>{!events.length && <p className="activity-empty">Evidence appears after the agents join. Start the demo to follow the checks.</p>}<div className="activity-storage"><Database size={15} /><span>Stored in this demo session<small>Databricks delivery is not connected.</small></span></div></aside>;
}

function Review({ demo, inspect, exportReview, onWorkstreams, onFile }: { demo: DemoState; inspect: (value: Inspector) => void; exportReview: () => void; onWorkstreams: () => void; onFile: (index: number) => void }) {
  if (demo.phase !== 'complete') return <section className="locked-review"><LockKeyhole size={29} /><h2>A shared review needs compatible work.</h2><p>Complete the identity, contract, and ChangeSet steps before reviewing the objective.</p><ul><li>{hasIdentity(demo.phase) ? <Check size={15} /> : <Circle size={13} />}Agent identities checked</li><li>{isAligned(demo.phase) ? <Check size={15} /> : <Circle size={13} />}Contract mismatch resolved</li><li><Circle size={13} />Both ChangeSets submitted</li></ul><Button onClick={onWorkstreams}>Return to workstreams<ArrowRight size={15} /></Button></section>;
  return <section className="review"><div className="review-banner"><span className="review-seal"><CheckCheck size={25} /></span><div><h2>Independent work. One coherent result.</h2><p>Both workstreams completed the demo with a compatible contract.</p></div></div><div className="review-summary"><span><ShieldCheck size={16} /><strong>2</strong> demo contributors</span><span><FileCode2 size={16} /><strong>4</strong> sample files</span><span><GitCompareArrows size={16} /><strong>1</strong> conflict resolved</span></div><div className="section-heading"><h3>Acceptance criteria</h3><Badge tone="green">Demo complete</Badge></div><ul className="review-criteria"><li><Check size={15} />Both identities checked against the demo fixture.</li><li><Check size={15} />Both agents declare <code>{'{ token, user }'}</code>.</li><li><Check size={15} />Frontend dependency satisfied by the backend contract.</li><li><Check size={15} />Two sample manifests submitted for review.</li></ul><div className="section-heading review-section"><h3>Submitted files</h3><span className="muted">Illustrative manifests</span></div><FileList onSelect={onFile} submitted /><div className="section-heading review-section"><h3>Reported tests</h3><button className="text-button" onClick={() => inspect({ kind: 'tests' })}>Inspect reports<ArrowUpRight size={13} /></button></div><TestRows completed /><div className="review-resolution"><GitCompareArrows size={18} /><div><strong>Prevented: incompatible authentication response</strong><p>Frontend changed <code>accessToken / profile</code> to <code>token / user</code>, following ADR-001.</p><button className="text-button" onClick={() => inspect({ kind: 'decision' })}>Read the supporting decision<ArrowUpRight size={13} /></button></div></div><div className="review-footer"><span>Demo evidence only. Tests were not executed; events were not sent to Databricks.</span><Button variant="primary" onClick={exportReview}><Download size={15} />Export review</Button></div></section>;
}

function Integrations({ backend, inspect }: { backend: ReturnType<typeof useBackend>; inspect: (value: Inspector) => void }) {
  return <div className="destination-page"><div className="page-heading"><div><h1>Integrations</h1><p>Know who is acting. Know why a decision was made.</p></div></div><div className="integration-list"><section className="integration-row"><div className="integration-symbol"><ShieldCheck size={24} /></div><div><h2>GoDaddy ANS</h2><p>Registered agent identities and verification evidence.</p><dl className="detail-list"><div><dt>Current adapter</dt><dd>{backend.data?.health.identity_mode ?? 'Unavailable'}</dd></div><div><dt>Live verification</dt><dd>Not implemented</dd></div><div><dt>Required configuration</dt><dd><code>ANS_BASE_URL · ANS_API_KEY · ANS_API_SECRET</code></dd></div></dl><Button onClick={() => inspect({ kind: 'identity' })}>Inspect demo identity<ArrowUpRight size={14} /></Button></div><Badge tone="amber">Not connected</Badge></section><section className="integration-row"><div className="integration-symbol"><Database size={24} /></div><div><h2>Databricks</h2><p>Architectural decisions and the objective event log.</p><dl className="detail-list"><div><dt>Current adapter</dt><dd>{backend.data?.health.memory_mode ?? 'Unavailable'}</dd></div><div><dt>Live reads / writes</dt><dd>Not implemented</dd></div><div><dt>Planned tables</dt><dd><code>synapse_decisions · synapse_events</code></dd></div></dl><Button onClick={() => inspect({ kind: 'decision' })}>Inspect local decision<ArrowUpRight size={14} /></Button></div><Badge tone="amber">Not connected</Badge></section><section className="integration-row"><div className="integration-symbol"><Terminal size={24} /></div><div><h2>Local coordinator</h2><p>The foundation API serves health and seeded workspace data.</p><dl className="detail-list"><div><dt>API address</dt><dd><code>127.0.0.1:8000</code></dd></div><div><dt>Last response</dt><dd>{backend.updatedAt?.toLocaleTimeString() ?? 'Waiting for a response'}</dd></div></dl><Button onClick={backend.retry}>Refresh connection<RotateCcw size={14} /></Button></div><Badge tone={backend.error ? 'amber' : backend.data ? 'green' : 'neutral'}>{backend.error ? 'Unavailable' : backend.data ? 'Connected' : 'Checking'}</Badge></section></div><p className="inline-note">Credentials stay on the server. This frontend never reads or stores provider secrets.</p></div>;
}

function BackendView({ backend, onDemo }: { backend: ReturnType<typeof useBackend>; onDemo: () => void }) {
  const state = backend.data?.state;
  return <div className="destination-page"><div className="page-heading"><div><h1>Backend workspace</h1><p>Actual API state, separate from the interactive walkthrough.</p></div><Button onClick={backend.retry}><RotateCcw size={14} />Refresh</Button></div>{backend.error && <div className="backend-error" role="alert"><TriangleAlert size={20} /><div><strong>Cannot reach the local coordinator</strong><p>{backend.error}</p><code>npm run dev:server</code>{state && <p>Showing the last received state from {backend.updatedAt?.toLocaleTimeString()}.</p>}</div></div>}{!state && !backend.error && <div className="skeleton-stack" aria-label="Loading backend workspace"><div /><div /><div /></div>}{state && <><div className="backend-objective"><div className="section-heading"><h2>{state.objective?.title ?? 'No objective seeded'}</h2><Badge>{state.phase}</Badge></div><p>{state.objective?.description ?? 'Run npm run seed to prepare the local workspace.'}</p><ul>{state.objective?.acceptance_criteria.map(criterion => <li key={criterion}>{criterion}</li>)}</ul></div><div className="section-heading"><h2>Workstreams</h2><span className="muted">{state.workstreams?.length ?? 0} from API</span></div><div className="backend-workstreams">{state.workstreams?.map(workstream => <article key={workstream.id}><div className="section-heading"><h3>{workstream.title}</h3><Badge>{workstream.status ?? 'pending'}</Badge></div><p>{workstream.agent_id}</p><code>{workstream.owned_paths.join(', ')}</code><dl className="detail-list"><div><dt>Contract</dt><dd>{workstream.contract.method} {workstream.contract.path}</dd></div><div><dt>Response fields</dt><dd>{Object.keys(workstream.contract.response_fields ?? {}).join(', ') || 'None declared'}</dd></div></dl></article>)}</div><div className="backend-counts"><span>{state.agents?.filter(agent => agent.verified).length ?? 0} identities marked verified by the API</span><span>{state.events?.length ?? 0} events</span><span>{state.conflicts?.length ?? 0} conflicts</span><span>{state.decisions?.length ?? 0} local decisions</span></div></>}<div className="backend-help"><h2>The foundation is connected to the UI.</h2><p>Join, claim, correction, and ChangeSet endpoints are still to come. Explore their intended behavior in the interactive demo.</p><Button variant="primary" onClick={onDemo}>Open interactive demo<ArrowRight size={15} /></Button></div></div>;
}
