import { useEffect, useState, type KeyboardEvent } from 'react';
import { Activity, ArrowRight, ArrowUpRight, BookOpen, Box, Check, CheckCheck, Circle, CircleHelp, CirclePlay, Code2, Database, Download, FileCode2, FolderGit2, GitBranch, GitCompareArrows, GitMerge, Layers3, LockKeyhole, Menu, Network, Plug, RotateCcw, ShieldCheck, Terminal, TriangleAlert, X } from 'lucide-react';
import { AgentCard, Badge, Busy, Button, Diff, FileList, InspectorDrawer, Logo, TestRows, type Inspector } from './components';
import { decisions, demoFiles, demoTests, hasIdentity, isAligned, type DemoState, type Phase } from './demo';
import { useCoordinator } from './useCoordinator';

type Page = 'workspace' | 'repository' | 'memory' | 'integrations';
type Tab = 'workstreams' | 'changes' | 'review';
const pages: { id: Page; label: string; icon: typeof Layers3 }[] = [
  { id: 'workspace', label: 'Workspace', icon: Layers3 },
  { id: 'repository', label: 'Repository', icon: FolderGit2 },
  { id: 'memory', label: 'Project memory', icon: BookOpen },
  { id: 'integrations', label: 'Integrations', icon: Plug },
];

export function SimulationWorkspace({ onLive }: { onLive: () => void }) {
  const coordinator = useCoordinator();
  const { demo } = coordinator;
  const [page, setPage] = useState<Page>('workspace');
  const [tab, setTab] = useState<Tab>('workstreams');
  const [mode, setMode] = useState<'demo' | 'backend'>('demo');
  const [inspector, setInspector] = useState<Inspector>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [resetConfirm, setResetConfirm] = useState(false);
  const [selectedFile, setSelectedFile] = useState(0);
  const [toast, setToast] = useState('');

  useEffect(() => {
    if (demo.phase === 'complete') setTab('review');
  }, [demo.phase]);

  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(''), 4500);
    return () => clearTimeout(timer);
  }, [toast]);

  const navigate = (next: Page) => { setPage(next); setMobileNav(false); };
  const start = async () => {
    setPage('workspace'); setTab('workstreams');
    if (await coordinator.start()) setToast('Coordinator predicted three file collisions before edits began.');
  };
  const reset = async () => {
    if (!await coordinator.reset()) return;
    setResetConfirm(false); setTab('workstreams'); setPage('workspace');
    setToast('Coordinator workspace reset.');
  };
  const selectFile = (index: number) => { setSelectedFile(index); setPage('repository'); };
  const exportReview = () => {
    if (demo.phase !== 'complete') return;
    const report = { title: 'Synapse · OAuth coordination review', source: 'LOCAL COORDINATOR DEMO — not live sponsor evidence', outcome: 'Three agents completed isolated ChangeSets; no merge performed', preventedCollision: 'src/auth/session.ts', files: demoFiles.map(file => ({ path: file.path, owner: file.owner })), identity: 'Mock fixtures; no ANS verification', memory: 'Local decision fixtures; no Databricks write', tests: demoTests.map(test => ({ ...test, status: 'passed', source: 'agent_reported' })), events: demo.events };
    const url = URL.createObjectURL(new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' }));
    const link = document.createElement('a'); link.href = url; link.download = 'synapse-demo-review.json'; link.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000); setToast('Demo review exported with evidence labels.');
  };

  return <div className="app-shell">
    <a className="skip-link" href="#main-content">Skip to workspace</a>
    <aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`} aria-label="Workspace navigation">
      <div className="sidebar-brand"><Logo /><button className="icon-button mobile-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X size={19} /></button></div>
      <div className="team-switch"><div className="team-avatar">S</div><div><strong>Synapse team</strong><span>Hackathon workspace</span></div><Badge>Demo</Badge></div>
      <nav className="primary-nav" aria-label="Main navigation">{pages.map(item => <button key={item.id} className={`nav-item ${page === item.id ? 'current' : ''}`} aria-current={page === item.id ? 'page' : undefined} onClick={() => navigate(item.id)}><item.icon size={18} /><span>{item.label}</span>{item.id === 'workspace' && <span className="nav-count">1</span>}</button>)}</nav>
      <div className="sidebar-objectives"><span className="sidebar-label">Active objective</span><button className="objective-nav" onClick={() => { navigate('workspace'); setTab('workstreams'); }}><span className={`status-dot ${demo.phase === 'complete' ? 'complete' : 'active'}`} /><span>Organization OAuth</span></button><div className="objective-branch"><GitBranch size={13} /><span>3 workstreams</span></div></div>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => setInspector({ kind: 'guide' })}><CircleHelp size={18} />Demo walkthrough<ArrowUpRight size={14} /></button><div className="sidebar-divider" /><div className="user-row"><span className="user-avatar">SY</span><div><strong>Local workspace</strong><span>No account required</span></div><span className="status-dot active" /></div></div>
    </aside>
    {mobileNav && <button className="nav-scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}

      <div className="app-main"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu size={20} /></button><FolderGit2 size={17} /><span className="repo-owner">synapse</span><span className="slash">/</span><strong>oauth-demo</strong><Badge><GitBranch size={12} />main</Badge></div><div className="topbar-right"><button className="connection-link" onClick={() => { setPage('integrations'); }}><span className={`status-dot ${coordinator.error ? 'offline' : coordinator.connected ? 'active' : 'waiting'}`} />{coordinator.error ? 'Coordinator offline' : coordinator.connected ? 'Coordinator connected' : 'Connecting'}</button><a className="icon-button" href="https://github.com/Jeewant05/VT-Hacks-14-Project" target="_blank" rel="noreferrer" aria-label="Open source repository on GitHub"><ArrowUpRight size={18} /></a></div></header>

      <div className="environment-bar"><div><Box size={15} /><strong>{mode === 'demo' ? 'Coordinator demo' : 'Raw workspace state'}</strong><span>{mode === 'demo' ? 'Real local API · mock identity · cache memory.' : 'Read-only view of the same coordinator state.'}</span></div><div className="environment-actions"><Button variant="quiet" onClick={onLive}><Activity size={14} />Live agents</Button><div className="mode-switch" aria-label="Workspace view"><button aria-pressed={mode === 'demo'} onClick={() => setMode('demo')}>Demo</button><button aria-pressed={mode === 'backend'} onClick={() => setMode('backend')}>Raw state</button></div></div></div>

      {coordinator.error && <div className="coordinator-alert" role="alert"><TriangleAlert size={17} /><span><strong>Coordinator unavailable.</strong> {coordinator.error}</span><Button onClick={coordinator.refresh}>Retry connection</Button></div>}

      <main id="main-content" tabIndex={-1}>
        {mode === 'backend' ? <BackendView coordinator={coordinator} onDemo={() => setMode('demo')} /> : <>
          {page === 'workspace' && <><div className="objective-header"><div className="objective-meta"><span className="objective-id"><Network size={14} />Objective SYN-001</span><Badge tone={demo.phase === 'complete' ? 'green' : demo.phase === 'conflict' || demo.phase === 'coordinating' ? 'amber' : 'neutral'}>{demo.phase === 'complete' ? 'Ready for review' : demo.phase === 'conflict' || demo.phase === 'coordinating' ? 'Needs attention' : 'In progress'}</Badge></div><div className="objective-title-row"><div><h1>Add organization-level OAuth login</h1><p>You and two teammates. Three coding agents. One repository without the collision.</p></div><div className="objective-actions">{demo.phase !== 'ready' && <Button variant="quiet" disabled={coordinator.busy} onClick={() => setResetConfirm(true)}><RotateCcw size={14} />Reset demo</Button>}{demo.phase === 'ready' && <Button variant="primary" disabled={!coordinator.connected || coordinator.busy} onClick={() => void start()}>{coordinator.pending === 'start' ? <Busy>Connecting agents</Busy> : <><CirclePlay size={16} />Run team demo</>}</Button>}{demo.phase === 'complete' && <Button onClick={exportReview}><Download size={15} />Export review</Button>}</div></div><div className="acceptance-list"><span><Check size={13} />Intent before edits</span><span>{hasIdentity(demo.phase) ? <Check size={13} /> : <Circle size={11} />}Three agent identities</span><span>{isAligned(demo.phase) ? <Check size={13} /> : <Circle size={11} />}Exclusive file ownership</span><span>{demo.phase === 'complete' ? <Check size={13} /> : <Circle size={11} />}Combined review</span></div></div>
          <Progress phase={demo.phase} />
          <div className="workspace-tabs" role="tablist" aria-label="Objective sections" onKeyDown={(event: KeyboardEvent<HTMLDivElement>) => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const values: Tab[] = ['workstreams', 'changes', 'review']; const index = values.indexOf(tab); const next = event.key === 'Home' ? 0 : event.key === 'End' ? 2 : (index + (event.key === 'ArrowRight' ? 1 : 2)) % 3; setTab(values[next]); event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]')[next].focus(); }}>
            <button role="tab" id="tab-workstreams" aria-controls="objective-panel" aria-selected={tab === 'workstreams'} tabIndex={tab === 'workstreams' ? 0 : -1} onClick={() => setTab('workstreams')}><Network size={16} />Workstreams<span>3</span></button>
            <button role="tab" id="tab-changes" aria-controls="objective-panel" aria-selected={tab === 'changes'} tabIndex={tab === 'changes' ? 0 : -1} onClick={() => setTab('changes')}><GitCompareArrows size={16} />Changes<span>{demo.phase === 'complete' ? demoFiles.length : '0'}</span></button>
            <button role="tab" id="tab-review" aria-controls="objective-panel" aria-selected={tab === 'review'} tabIndex={tab === 'review' ? 0 : -1} onClick={() => setTab('review')}><GitMerge size={16} />Convergence{demo.phase !== 'complete' && <LockKeyhole size={12} />}</button>
          </div>
          <div className="workspace-grid"><div className="workspace-content" role="tabpanel" id="objective-panel" aria-labelledby={`tab-${tab}`}>
            {tab === 'workstreams' && <><StagePanel demo={demo} start={() => void start()} inspect={setInspector} accept={() => void coordinator.applyPlan()} submit={() => void coordinator.submit()} openReview={() => setTab('review')} /><div className="section-heading agent-plans-heading"><h2>Agent work plans</h2><span className="muted">{demo.phase === 'complete' ? '3 complete' : 'Intent published before coding'}</span></div><div className="agent-grid"><AgentCard role="backend" phase={demo.phase} inspect={setInspector} /><AgentCard role="frontend" phase={demo.phase} inspect={setInspector} /><AgentCard role="telemetry" phase={demo.phase} inspect={setInspector} /></div>
            <div className={`scope-summary ${!isAligned(demo.phase) && demo.phase !== 'ready' ? 'scope-summary-warning' : ''}`}><ShieldCheck size={15} /><span>{isAligned(demo.phase) ? 'One owner per file.' : demo.phase === 'ready' ? 'Waiting for agent intent.' : 'Shared file detected in 3 plans.'}</span><code>src/auth/session.ts</code><span className="scope-clear">{isAligned(demo.phase) ? 'Owned by your API agent' : demo.phase === 'ready' ? 'Preflight pending' : 'Coding paused'}</span></div></>}
            {tab === 'changes' && <><div className="section-heading"><h2>ChangeSets</h2><Badge>{demo.phase === 'complete' ? '3 submitted · Demo' : 'Awaiting submissions'}</Badge></div><p className="section-description">{demo.phase === 'complete' ? 'All three workstreams submitted non-overlapping manifests. Select a file to inspect its illustrative changes.' : 'The sample manifests become eligible only after the coordinator assigns one owner to every file.'}</p><FileList onSelect={selectFile} submitted={demo.phase === 'complete'} /><div className="inline-note"><FileCode2 size={16} />Sample manifests only. No files in your Git repository are modified.</div></>}
            {tab === 'review' && <Review demo={demo} inspect={setInspector} exportReview={exportReview} onWorkstreams={() => setTab('workstreams')} onFile={selectFile} />}
          </div><ActivityFeed demo={demo} inspect={setInspector} /></div></>}
          {page === 'repository' && <div className="destination-page"><div className="page-heading"><div><h1>Repository</h1><p>Inspect the files behind the three coordinated workstreams.</p></div><Badge>Illustrative demo repository</Badge></div><div className="repo-toolbar"><span><GitBranch size={15} />main</span><span>oauth-demo / src</span><span className="muted">{demoFiles.length} sample files</span></div><FileList selected={selectedFile} onSelect={setSelectedFile} submitted={demo.phase === 'complete'} /><Diff index={selectedFile} /><div className="inline-note"><CircleHelp size={16} />These excerpts are authored demo material. The actual project lives in VT-Hacks-14-Project.</div></div>}
          {page === 'memory' && <div className="destination-page"><div className="page-heading"><div><h1>Project memory</h1><p>The decisions that keep independent agents working from the same context.</p></div><Badge tone="amber">Local fixtures</Badge></div><div className="memory-intro"><Database size={21} /><div><strong>Governed decisions, at the point of work.</strong><p>The live integration will retrieve these decisions from Databricks. This demo uses three local examples.</p></div></div><div className="decision-list">{decisions.map(decision => <button className="decision-row" key={decision.id} onClick={() => setInspector({ kind: 'decision', id: decision.id })}><BookOpen size={20} /><div><div className="decision-title"><h2>{decision.title}</h2>{decision.relevant && <Badge tone="green">Relevant to objective</Badge>}</div><p>{decision.summary}</p><span>{decision.id} <span className="separator-dot">·</span> {decision.component} <span className="separator-dot">·</span> Local copy</span></div><ArrowUpRight size={17} /></button>)}</div></div>}
          {page === 'integrations' && <Integrations coordinator={coordinator} inspect={setInspector} />}
        </>}
      </main>
      <footer className="workspace-footer"><span><span className={`status-dot ${coordinator.connected ? 'active' : 'offline'}`} />{mode === 'demo' ? 'Local coordinator' : 'Raw coordinator state'}</span><span>Built for coordination. Grounded in evidence.</span><span>Synapse / MVP</span></footer>
    </div>
    <InspectorDrawer value={inspector} onClose={() => setInspector(null)} demo={demo} />
    {resetConfirm && <div className="reset-confirm" role="alert"><div><strong>Reset this demo?</strong><span>Replace the local coordinator workspace with the seeded objective.</span></div><Button onClick={() => setResetConfirm(false)}>Keep progress</Button><Button variant="primary" disabled={coordinator.busy} onClick={() => void reset()}>{coordinator.pending === 'reset' ? <Busy>Resetting</Busy> : 'Reset demo'}</Button></div>}
    <div className={`toast ${toast ? 'toast-visible' : ''}`} role="status">{toast && <><Check size={16} />{toast}</>}</div>
    <div className="sr-only" role="status">{demo.phase === 'conflict' ? 'Overlapping file intent detected. Review the coordination plan.' : demo.phase === 'aligned' ? 'File ownership is isolated. Submit demo ChangeSets to continue.' : demo.phase === 'complete' ? 'Demo complete. Convergence review is available.' : ''}</div>
  </div>;
}

function Progress({ phase }: { phase: Phase }) {
  const step = phase === 'ready' ? 0 : ['verifying', 'context'].includes(phase) ? 1 : phase === 'complete' ? 3 : 2;
  return <ol className="progress-steps" aria-label="Objective progress">{['Objective created', 'Intent published', 'Ownership assigned', 'Ready for review'].map((label, index) => <li key={label} className={`${index < step || phase === 'complete' ? 'done' : ''} ${index === step ? 'current' : ''} ${index === 2 && ['conflict', 'coordinating'].includes(phase) ? 'attention' : ''}`} aria-current={index === step ? 'step' : undefined}><span>{index < step || phase === 'complete' ? <Check size={13} /> : index === 2 && ['conflict', 'coordinating'].includes(phase) ? <TriangleAlert size={12} /> : <span>{index + 1}</span>}</span><span>{index === 2 && ['conflict', 'coordinating'].includes(phase) ? 'File collision' : label}</span></li>)}</ol>;
}

function StagePanel({ demo, start, accept, submit, inspect, openReview }: { demo: DemoState; start: () => void; accept: () => void; submit: () => void; inspect: (value: Inspector) => void; openReview: () => void }) {
  const { phase } = demo;
  if (phase === 'ready' || phase === 'verifying' || phase === 'context') return <section className="ready-panel"><div className="ready-diagram ready-diagram-three" aria-hidden="true"><Code2 size={23} /><span /><Code2 size={23} /><span /><Code2 size={23} /></div><h2>{phase === 'ready' ? 'Catch the collision before anyone writes code.' : phase === 'verifying' ? 'Connecting three coding agents…' : 'Agents are publishing their work plans…'}</h2><p>{phase === 'ready' ? 'Watch your agent and two teammate agents independently choose the same shared file, then let Synapse reorganize the work before implementation starts.' : phase === 'verifying' ? 'The walkthrough uses local identity fixtures while the GoDaddy ANS adapter is pending.' : 'Each agent declares the files it expects to touch. The coordinator compares all three plans.'}</p>{phase === 'ready' ? <Button variant="primary" onClick={start}><CirclePlay size={16} />Run team demo<ArrowRight size={15} /></Button> : <Busy>{phase === 'verifying' ? 'Checking three identities' : 'Comparing planned file touches'}</Busy>}<span className="ready-footnote">{phase === 'ready' ? 'About 30 seconds · You approve the new ownership plan' : 'Coordinator API · No repository edits yet'}</span></section>;
  const rows = [
    { name: 'Your API agent', before: 'src/auth/session.ts', after: 'Owns session.ts' },
    { name: 'Teammate A · UI', before: 'src/auth/session.ts', after: 'OrganizationLogin.tsx' },
    { name: 'Teammate B · Telemetry', before: 'src/auth/session.ts', after: 'authEvents.ts' },
  ];
  return <section className={`coordination-panel ${isAligned(phase) ? 'panel-aligned' : 'panel-conflict'}`} aria-labelledby="coordination-title"><div className="coordination-heading"><div className="coordination-icon">{isAligned(phase) ? <CheckCheck size={21} /> : <GitCompareArrows size={21} />}</div><div><h2 id="coordination-title">{phase === 'complete' ? 'The merge conflict never happened.' : isAligned(phase) ? 'Three agents now have clean boundaries.' : 'Three agents chose the same file.'}</h2><p>{phase === 'complete' ? 'Independent ChangeSets are ready for one combined review.' : isAligned(phase) ? 'One owner keeps the shared session module; teammates integrate through stable boundaries.' : 'Synapse paused all three plans before any agent edited src/auth/session.ts.'}</p></div><Badge tone={isAligned(phase) ? 'green' : 'amber'}>{isAligned(phase) ? 'Coordinated' : 'Preflight blocked'}</Badge></div>
    <div className="collision-map"><div className="collision-map-head"><span>Agent</span><span>{isAligned(phase) ? 'Original intent' : 'Planned touch'}</span><span>{isAligned(phase) ? 'Assigned scope' : 'Collision'}</span></div>{rows.map(row => <div className="collision-map-row" key={row.name}><strong>{row.name}</strong><code>{row.before}</code><span className={isAligned(phase) ? 'assignment-clear' : 'assignment-conflict'}>{isAligned(phase) ? <><Check size={14} />{row.after}</> : <><TriangleAlert size={14} />Same file</>}</span></div>)}</div>
    <button className="decision-evidence" onClick={() => inspect({ kind: 'decision', id: 'ADR-002' })}><Database size={19} /><span><strong>Project memory defines the boundary.</strong><span>ADR-002 assigns one editor to shared session logic and keeps consumers in separate modules.</span><small>Databricks decision · Local demo copy</small></span><ArrowUpRight size={17} /></button>
    <div className="resolution-action"><span>{phase === 'conflict' ? 'Recommended: keep session.ts with the API owner and redirect UI and telemetry work.' : phase === 'coordinating' ? 'Writing the approved ownership plan to all three workstreams.' : phase === 'aligned' ? 'The agents can now implement independently and submit non-overlapping manifests.' : phase === 'submitting' ? 'Collecting three manifests and agent-reported tests.' : 'No automatic merge. The team keeps final review control.'}</span>{phase === 'conflict' ? <Button variant="primary" onClick={accept}>Apply coordination plan<ArrowRight size={15} /></Button> : phase === 'coordinating' ? <Button disabled><Busy>Reassigning file scopes</Busy></Button> : phase === 'aligned' ? <Button variant="primary" onClick={submit}>Run agents & submit ChangeSets<ArrowRight size={15} /></Button> : phase === 'submitting' ? <Button disabled><Busy>Checking three manifests</Busy></Button> : <Button variant="primary" onClick={openReview}>Open review<ArrowRight size={15} /></Button>}</div>
  </section>;
}

function ActivityFeed({ demo, inspect }: { demo: DemoState; inspect: (value: Inspector) => void }) {
  const [filter, setFilter] = useState<'all' | 'important'>('all');
  const events = demo.events.filter(event => filter === 'all' || event.evidence);
  return <aside className="activity-panel" aria-label="Coordination activity"><div className="activity-heading"><h2><Activity size={17} />Activity</h2><span className="source-tag">Coordinator</span></div><div className="activity-filter"><button aria-pressed={filter === 'all'} onClick={() => setFilter('all')}>All events<span>{demo.events.length}</span></button><button aria-pressed={filter === 'important'} onClick={() => setFilter('important')}>Evidence</button></div><ol className="timeline">{events.map(event => <li key={event.id} className={`event-${event.tone}`}><span className="event-marker">{event.tone === 'success' ? <Check size={11} /> : event.tone === 'warning' ? <TriangleAlert size={10} /> : <span />}</span><div className="event-content"><div><strong>{event.title}</strong><time>{event.time}</time></div><p>{event.detail}</p>{event.evidence && <button onClick={() => inspect({ kind: event.evidence! })}>View evidence<ArrowUpRight size={12} /></button>}</div></li>)}</ol>{!events.length && <p className="activity-empty">Evidence appears after the agents join. Start the demo to follow the checks.</p>}<div className="activity-storage"><Database size={15} /><span>Stored in local SQLite<small>Databricks delivery is not connected.</small></span></div></aside>;
}

function Review({ demo, inspect, exportReview, onWorkstreams, onFile }: { demo: DemoState; inspect: (value: Inspector) => void; exportReview: () => void; onWorkstreams: () => void; onFile: (index: number) => void }) {
  if (demo.phase !== 'complete') return <section className="locked-review"><LockKeyhole size={29} /><h2>A shared review needs coordinated work.</h2><p>Assign exclusive file ownership and collect all three ChangeSets before reviewing the objective.</p><ul><li>{hasIdentity(demo.phase) ? <Check size={15} /> : <Circle size={13} />}Three agent identities checked</li><li>{isAligned(demo.phase) ? <Check size={15} /> : <Circle size={13} />}Overlapping intent reorganized</li><li><Circle size={13} />Three ChangeSets submitted</li></ul><Button onClick={onWorkstreams}>Return to workstreams<ArrowRight size={15} /></Button></section>;
  return <section className="review"><div className="review-banner"><span className="review-seal"><CheckCheck size={25} /></span><div><h2>Independent agents. One conflict-free plan.</h2><p>All three workstreams completed without sharing an edited file.</p></div></div><div className="review-summary"><span><ShieldCheck size={16} /><strong>3</strong> demo contributors</span><span><FileCode2 size={16} /><strong>{demoFiles.length}</strong> sample files</span><span><GitCompareArrows size={16} /><strong>3</strong> pairwise conflicts across <strong>1</strong> shared file</span></div><div className="section-heading"><h3>Acceptance criteria</h3><Badge tone="green">Demo complete</Badge></div><ul className="review-criteria"><li><Check size={15} />Three identities checked against the demo fixture.</li><li><Check size={15} />Overlapping intent detected before implementation.</li><li><Check size={15} /><code>src/auth/session.ts</code> assigned to one owner.</li><li><Check size={15} />Three non-overlapping manifests enforced and submitted.</li></ul><div className="section-heading review-section"><h3>Submitted files</h3><span className="muted">Illustrative manifests</span></div><FileList onSelect={onFile} submitted /><div className="section-heading review-section"><h3>Reported tests</h3><button className="text-button" onClick={() => inspect({ kind: 'tests' })}>Inspect reports<ArrowUpRight size={13} /></button></div><TestRows completed /><div className="review-resolution"><GitCompareArrows size={18} /><div><strong>Prevented: three agents editing the shared session module</strong><p>The coordinator kept <code>src/auth/session.ts</code> with the API agent and rejected files outside each assigned scope.</p><button className="text-button" onClick={() => inspect({ kind: 'decision', id: 'ADR-002' })}>Read the ownership decision<ArrowUpRight size={13} /></button></div></div><div className="review-footer"><span>Demo evidence only. Tests were agent-reported; events were not sent to Databricks.</span><Button variant="primary" onClick={exportReview}><Download size={15} />Export review</Button></div></section>;
}

function Integrations({ coordinator, inspect }: { coordinator: ReturnType<typeof useCoordinator>; inspect: (value: Inspector) => void }) {
  return <div className="destination-page"><div className="page-heading"><div><h1>Integrations</h1><p>Know who is acting. Know why a decision was made.</p></div></div><div className="integration-list"><section className="integration-row"><div className="integration-symbol"><ShieldCheck size={24} /></div><div><h2>GoDaddy ANS</h2><p>Registered agent identities and verification evidence.</p><dl className="detail-list"><div><dt>Current adapter</dt><dd>{coordinator.health?.identity_mode ?? 'Unavailable'}</dd></div><div><dt>Live verification</dt><dd>Not implemented</dd></div><div><dt>Required configuration</dt><dd><code>ANS_BASE_URL · ANS_API_KEY · ANS_API_SECRET</code></dd></div></dl><Button onClick={() => inspect({ kind: 'identity' })}>Inspect coordinator identity<ArrowUpRight size={14} /></Button></div><Badge tone="amber">Mock adapter</Badge></section><section className="integration-row"><div className="integration-symbol"><Database size={24} /></div><div><h2>Databricks</h2><p>Architectural decisions and the objective event log.</p><dl className="detail-list"><div><dt>Current adapter</dt><dd>{coordinator.health?.memory_mode ?? 'Unavailable'}</dd></div><div><dt>Live reads / writes</dt><dd>Not implemented</dd></div><div><dt>Planned tables</dt><dd><code>synapse_decisions · synapse_events</code></dd></div></dl><Button onClick={() => inspect({ kind: 'decision' })}>Inspect attached decision<ArrowUpRight size={14} /></Button></div><Badge tone="amber">Cache adapter</Badge></section><section className="integration-row"><div className="integration-symbol"><Terminal size={24} /></div><div><h2>Local coordinator</h2><p>The UI calls the join, claim, declare, correction, submission, state, and reset endpoints.</p><dl className="detail-list"><div><dt>API address</dt><dd><code>127.0.0.1:8000</code></dd></div><div><dt>Last response</dt><dd>{coordinator.updatedAt?.toLocaleTimeString() ?? 'Waiting for a response'}</dd></div></dl><Button onClick={coordinator.refresh}>Refresh connection<RotateCcw size={14} /></Button></div><Badge tone={coordinator.error ? 'amber' : coordinator.connected ? 'green' : 'neutral'}>{coordinator.error ? 'Unavailable' : coordinator.connected ? 'Connected' : 'Checking'}</Badge></section></div><p className="inline-note">Credentials stay on the server. This frontend never reads or stores provider secrets.</p></div>;
}

function BackendView({ coordinator, onDemo }: { coordinator: ReturnType<typeof useCoordinator>; onDemo: () => void }) {
  const state = coordinator.workspace;
  return <div className="destination-page"><div className="page-heading"><div><h1>Coordinator workspace</h1><p>Raw API state behind the guided walkthrough.</p></div><Button onClick={coordinator.refresh}><RotateCcw size={14} />Refresh</Button></div>{coordinator.error && <div className="backend-error" role="alert"><TriangleAlert size={20} /><div><strong>Cannot reach the local coordinator</strong><p>{coordinator.error}</p><code>npm run dev:server</code>{state && <p>Showing the last received state from {coordinator.updatedAt?.toLocaleTimeString()}.</p>}</div></div>}{!state && !coordinator.error && <div className="skeleton-stack" aria-label="Loading coordinator workspace"><div /><div /><div /></div>}{state && <><div className="backend-objective"><div className="section-heading"><h2>{state.objective?.title ?? 'No objective seeded'}</h2><Badge>{state.objective?.status ?? state.phase}</Badge></div><p>{state.objective?.description ?? 'Run npm run seed to prepare the local workspace.'}</p><ul>{state.objective?.acceptance_criteria.map(criterion => <li key={criterion}>{criterion}</li>)}</ul></div><div className="section-heading"><h2>Workstreams</h2><span className="muted">{state.workstreams?.length ?? 0} from API</span></div><div className="backend-workstreams">{state.workstreams?.map(workstream => <article key={workstream.id}><div className="section-heading"><h3>{workstream.title}</h3><Badge>{workstream.status ?? 'pending'}</Badge></div><p>{workstream.agent_id}</p><code>{workstream.owned_paths.join(', ')}</code><dl className="detail-list"><div><dt>Contract</dt><dd>{workstream.contract.method} {workstream.contract.path}</dd></div><div><dt>Response fields</dt><dd>{Object.keys(workstream.contract.response_fields ?? {}).join(', ') || 'None declared'}</dd></div></dl></article>)}</div><div className="backend-counts"><span>{state.agents?.filter(agent => agent.verified).length ?? 0} identities marked verified by the API</span><span>{state.events?.length ?? 0} events</span><span>{state.conflicts?.filter(conflict => conflict.status === 'open').length ?? 0} open conflicts</span><span>{state.decisions?.length ?? 0} local decisions</span></div></>}<div className="backend-help"><h2>The coordinator is connected to the UI.</h2><p>The guided demo uses this same workspace for identity checks, declarations, conflict resolution, and ChangeSet submission.</p><Button variant="primary" onClick={onDemo}>Open guided workspace<ArrowRight size={15} /></Button></div></div>;
}
